### ISSUE TITLE
Request for Detailed README for Code Execution

### ISSUE THREAD

**Issue by sehyun03** [lygjwy/DOS#1]
Hello,

Firstly, I would like to express my gratitude for sharing your code with the community; it's greatly appreciated.

However, I am encountering some challenges with running the code due to the need for dataset preparation, installing specific packages, and executing the training and testing scripts. Could you please provide a detailed README or documentation that outlines the steps for setting up and running the code?

Thank you very much for your assistance!

**Comment by lygjwy** [comment]
Thanks for the heads up, I'll be updating the detailed README documentation in the following week!

**Comment by YutingLi0606** [comment]
> Thanks for the heads up, I'll be updating the detailed README documentation in the following week!

Hi~ We all need your README！
Your code is comprehensive enough but there is no README file. Could you please provide a detailed README？（Including comments for each python file like detect.py , train_unsa_dual_sp.py）

**Comment by lygjwy** [comment]
Thanks for your kind reminders. I have updated the repo with a detailed README. If you have any questions about the code, please feel free to ask.
